# Generated by Django 5.2.6 on 2025-09-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudproject", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-date_joined"]},
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
